<?php
namespace HurahCli\Package;

use Composer\Command\BaseCommand;
use Hi\Helpers\DirectoryStructure;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;


class Find extends BaseCommand
{
    protected function configure()
    {
        $this->setName("novum:package-find");
        $this->setDescription("List / find installable packages");
        // $this->addOption('verbose', 'v', InputOption::VALUE_NONE);
    }
    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        parent::initialize($input, $output); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $oDirectoryStructure = new DirectoryStructure();
        $aDomains = $oDirectoryStructure->getDomainCollection();

        if(empty($aDomains))
        {
            $output->writeln("No domains found, you must first install a domain");
        }
        $output->writeln('Executing');
    }

}
